// Deterministic project scaffolding.
//
// Produces every wrapper/auxiliary file a generated prototype needs to
// actually run (`npm install && npm run dev`). These files are pure
// templates driven by the stack registry and the architect's contract;
// no LLM is involved. Keeping them out of the LLM packager removes the
// biggest source of broken alpha generations:
//
//   - missing `client/index.html` and `client/vite.config.js`
//   - root `package.json` with the wrong/stale deps
//   - mixed-stack files (stack-b output ending up with FastAPI's
//     `requirements.txt`, or stack-a with `better-sqlite3`)
//   - no Vite `/api` proxy, so frontend `fetch('/api/...')` calls hit
//     the dev server instead of the backend
//   - SQLAlchemy-style `DATABASE_URL` passed into `better-sqlite3`
//
// The scaffold writes its files AFTER the LLM packager runs, so any
// wrapper files the LLM may have produced are overwritten by canonical
// versions. The LLM packager keeps responsibility for prose-heavy files
// (README.md, DISCLAIMER.md).
//
// Public API:
//   scaffoldProject({ sessionId, projectName, stack, contract }) → string[]

import { getStack } from '../agents/stacks.js';
import { writeOutputFile } from '../sessions/sessionStore.js';

// ─────────────────────────────────────────────────────────────────────────────
// Pinned package versions
// ─────────────────────────────────────────────────────────────────────────────
//
// Pinned here so generated projects don't drift with whatever the
// npm registry served on the day they were generated. Bump in lockstep
// with DemoKit itself when its own client/server packages are upgraded.

const CLIENT_DEPS = Object.freeze({
  react: '^18.3.1',
  'react-dom': '^18.3.1',
  'react-router-dom': '^6.30.0',
});

const CLIENT_DEV_DEPS = Object.freeze({
  vite: '^5.4.0',
  '@vitejs/plugin-react': '^4.3.4',
  tailwindcss: '^4.1.0',
  '@tailwindcss/vite': '^4.1.0',
});

const STACK_B_SERVER_DEPS = Object.freeze({
  express: '^5.0.0',
  'better-sqlite3': '^11.0.0',
  cors: '^2.8.5',
  // `csv-parse` powers the optional "drop a CSV into server/seed-data/<table>.csv
  // and have it imported on first boot" workflow. Always shipped so the coder
  // can rely on it without re-architecting deps when the human runs the demo
  // with real data.
  'csv-parse': '^5.5.0',
});

const ROOT_DEV_DEPS = Object.freeze({
  concurrently: '^9.1.0',
});

const STACK_A_REQUIREMENTS = [
  'fastapi>=0.110,<1.0',
  'uvicorn[standard]>=0.27,<1.0',
  'sqlalchemy>=2.0,<3.0',
  'pydantic>=2.0,<3.0',
  '',
].join('\n');

// ─────────────────────────────────────────────────────────────────────────────
// File templates
// ─────────────────────────────────────────────────────────────────────────────

function indexHtml(projectName) {
  return [
    '<!doctype html>',
    '<html lang="en">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${escapeHtml(projectName)}</title>`,
    '  </head>',
    '  <body>',
    '    <div id="root"></div>',
    '    <script type="module" src="/src/main.jsx"></script>',
    '  </body>',
    '</html>',
    '',
  ].join('\n');
}

// Canonical bootstrap for the React app. Generated by the scaffold (not
// the LLM coder) so the BrowserRouter root is in exactly ONE place. This
// kills a whole class of "blank screen" bugs where the coder, having no
// signal about where the router should live, would emit <BrowserRouter>
// in both main.jsx AND App.jsx — react-router-dom then throws "you cannot
// render a <Router> inside another <Router>" and the tree fails to mount.
//
// The coder is told (in [CODE]) that BrowserRouter is provided here, so
// App.jsx must contain only <Routes>/<Route>. The evaluator's
// `frontend-renders-once` check enforces this at validation time.
//
// The ErrorBoundary wrapper turns any future render-time crash into a
// visible red panel instead of a blank page — debugger UX win for the
// human running the demo.
function mainJsx() {
  return [
    "import React from 'react';",
    "import ReactDOM from 'react-dom/client';",
    "import { BrowserRouter } from 'react-router-dom';",
    "import App from './App.jsx';",
    "import ErrorBoundary from './ErrorBoundary.jsx';",
    "import './index.css';",
    '',
    "ReactDOM.createRoot(document.getElementById('root')).render(",
    '  <React.StrictMode>',
    '    <ErrorBoundary>',
    '      <BrowserRouter>',
    '        <App />',
    '      </BrowserRouter>',
    '    </ErrorBoundary>',
    '  </React.StrictMode>',
    ');',
    '',
  ].join('\n');
}

// Top-level error boundary. Renders a visible red panel with the error
// message + stack when any descendant throws during render, instead of a
// blank page. Generated by the scaffold so projects always have it; the
// coder doesn't need to know it exists.
function errorBoundary() {
  return [
    "import React from 'react';",
    '',
    'export default class ErrorBoundary extends React.Component {',
    '  constructor(props) {',
    '    super(props);',
    '    this.state = { error: null };',
    '  }',
    '',
    '  static getDerivedStateFromError(error) {',
    '    return { error };',
    '  }',
    '',
    '  componentDidCatch(error, info) {',
    "    console.error('[ErrorBoundary] caught:', error, info);",
    '  }',
    '',
    '  render() {',
    '    if (this.state.error) {',
    '      return (',
    '        <div',
    '          role="alert"',
    "          style={{",
    "            margin: '1rem',",
    "            padding: '1rem',",
    "            border: '2px solid #dc2626',",
    "            borderRadius: '0.5rem',",
    "            background: '#fef2f2',",
    "            color: '#7f1d1d',",
    "            fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',",
    "            whiteSpace: 'pre-wrap',",
    '          }}',
    '        >',
    "          <h2 style={{ marginTop: 0, fontFamily: 'inherit' }}>",
    '            Something went wrong while rendering this page.',
    '          </h2>',
    '          <p>',
    '            <strong>{String(this.state.error?.message || this.state.error)}</strong>',
    '          </p>',
    '          {this.state.error?.stack && (',
    "            <pre style={{ fontSize: '0.75rem', overflow: 'auto' }}>",
    '              {this.state.error.stack}',
    '            </pre>',
    '          )}',
    '          <p>',
    '            <em>',
    '              This panel is rendered by a scaffolded ErrorBoundary. The',
    "              demo's React tree threw during render — check the browser",
    '              console for the full stack trace.',
    '            </em>',
    '          </p>',
    '        </div>',
    '      );',
    '    }',
    '    return this.props.children;',
    '  }',
    '}',
    '',
  ].join('\n');
}

function viteConfig(backendPort) {
  return [
    "import { defineConfig } from 'vite';",
    "import react from '@vitejs/plugin-react';",
    "import tailwindcss from '@tailwindcss/vite';",
    '',
    '// Vite dev server proxies /api to the backend so the frontend can',
    "// call `fetch('/api/...')` literally — no VITE_API_URL juggling, no",
    '// CORS preflights. Production deployments would replace this with a',
    '// reverse-proxy or by serving the built client from the backend.',
    'export default defineConfig({',
    '  plugins: [react(), tailwindcss()],',
    '  server: {',
    '    proxy: {',
    "      '/api': {",
    `        target: 'http://localhost:${backendPort}',`,
    '        changeOrigin: true,',
    '      },',
    '    },',
    '  },',
    '});',
    '',
  ].join('\n');
}

function clientPackageJson(projectName) {
  return (
    JSON.stringify(
      {
        name: `${projectName}-client`,
        private: true,
        version: '0.0.1',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
        },
        dependencies: { ...CLIENT_DEPS },
        devDependencies: { ...CLIENT_DEV_DEPS },
      },
      null,
      2
    ) + '\n'
  );
}

function stackBServerPackageJson(projectName) {
  return (
    JSON.stringify(
      {
        name: `${projectName}-server`,
        private: true,
        version: '0.0.1',
        type: 'module',
        main: 'index.js',
        scripts: {
          start: 'node index.js',
          dev: 'node --watch index.js',
        },
        dependencies: { ...STACK_B_SERVER_DEPS },
      },
      null,
      2
    ) + '\n'
  );
}

function rootPackageJsonStackB(projectName) {
  return (
    JSON.stringify(
      {
        name: projectName,
        private: true,
        version: '0.0.1',
        scripts: {
          // Root install is required to bring in `concurrently` (declared
          // as a root devDependency). Without it `npm run dev` fails with
          // `concurrently: command not found` even after `install:all`.
          'install:all':
            'npm install && npm --prefix client install && npm --prefix server install',
          dev: 'concurrently -k -n server,client -c cyan,magenta "npm:dev:server" "npm:dev:client"',
          'dev:client': 'npm --prefix client run dev',
          'dev:server': 'npm --prefix server run dev',
          build: 'npm --prefix client run build',
          start: 'npm --prefix server run start',
        },
        devDependencies: { ...ROOT_DEV_DEPS },
      },
      null,
      2
    ) + '\n'
  );
}

function rootPackageJsonStackA(projectName) {
  return (
    JSON.stringify(
      {
        name: projectName,
        private: true,
        version: '0.0.1',
        scripts: {
          'install:client': 'npm --prefix client install',
          'dev:client': 'npm --prefix client run dev',
          build: 'npm --prefix client run build',
        },
      },
      null,
      2
    ) + '\n'
  );
}

function envExample(contract) {
  const lines = [];
  const fe = (contract && contract.frontendEnv) || {};
  const be = (contract && contract.backendEnv) || {};

  if (Object.keys(fe).length > 0) {
    lines.push('# Frontend (Vite).');
    lines.push('# In dev the Vite proxy handles /api routing — these only');
    lines.push('# matter for production builds.');
    for (const [k, v] of Object.entries(fe)) {
      lines.push(`${k}=${v}`);
    }
    lines.push('');
  }

  if (Object.keys(be).length > 0) {
    lines.push('# Backend');
    for (const [k, v] of Object.entries(be)) {
      lines.push(`${k}=${v}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function gitignore() {
  return [
    'node_modules/',
    'dist/',
    '.env',
    '.env.local',
    '.venv/',
    '__pycache__/',
    '*.pyc',
    '*.sqlite',
    '*.sqlite3',
    '*.db',
    '.DS_Store',
    '',
  ].join('\n');
}

// README dropped into client/public/sample-assets/ to (a) keep the folder
// alive on disk / in git, and (b) tell the human running the demo where
// to drop their own static files. The DB seed references stable URLs in
// this folder (/sample-assets/<table>-<n>.<ext>); broken-link icons
// until the user drops files are an intentional "this is placeholder
// data" signal.
function sampleAssetsReadme(projectName) {
  return [
    `# Sample assets for ${projectName}`,
    '',
    'Vite serves everything under `client/public/` at the site root. Files placed in this directory are reachable at `/sample-assets/<filename>` from both the frontend and the seeded database rows.',
    '',
    '## What this folder is for',
    '',
    'This project was generated by DemoKit as a **client-facing prototype**. The backend auto-seeds each table on first boot, and any column that holds a URL to a static file points at this folder using a stable convention:',
    '',
    '```',
    '/sample-assets/<table>-1.<ext>',
    '/sample-assets/<table>-2.<ext>',
    '/sample-assets/<table>-3.<ext>',
    '...',
    '```',
    '',
    'Supported file types include but are not limited to:',
    '',
    '- Images — `.jpg`, `.png`, `.svg`, `.webp`, `.gif`',
    '- Documents — `.pdf`',
    '- Downloadable data — `.csv`, `.xlsx`, `.json`',
    '- Media — `.mp4`, `.webm`, `.mp3`, `.wav`',
    '- Archives — `.zip`',
    '',
    "DemoKit doesn't ship binary assets with the generated code, so the folder ships empty. Until you drop files here, the page renders broken-image icons or broken-link icons — that's the intended visual reminder that this is placeholder data.",
    '',
    '## How to populate it',
    '',
    '1. Look at the seeded rows in your SQLite database (or `server/db.js` / `server/database.py`) to see which filenames are referenced.',
    '2. Drop matching files into this folder using those exact names.',
    '3. Refresh the browser — Vite picks new files up immediately, no restart required.',
    '',
    'For a production build, `vite build` copies everything in `public/` into `dist/`, so the same files keep working.',
    '',
    '## Want to demo with REAL row data, not just real files?',
    '',
    'See `server/seed-data/README.md`. Drop a CSV named `<table>.csv` into that folder and the backend imports your rows on first boot — no code edits needed.',
    '',
  ].join('\n');
}

// README dropped into server/seed-data/ for the "real data import"
// workflow. The coder's seed block looks for <table>.csv in this folder
// first; if found, it parses it (csv-parse on stack-b, stdlib csv on
// stack-a) and INSERTs those rows; otherwise it falls back to
// lorem-ipsum placeholders. The folder ships empty so the user has to
// opt in — silent overwrite of carefully-curated CSVs is worse than a
// loud "drop your file here" affordance.
function seedDataReadme(projectName) {
  return [
    `# Real seed data for ${projectName}`,
    '',
    "Drop CSV files here to import real rows into the database on first boot. This is the simplest way to demo with realistic data without editing code.",
    '',
    '## How it works',
    '',
    "When the backend starts and a table is empty (e.g. on first run, or after you delete `dev.db`), the DB init file looks for a CSV in this folder named after the table:",
    '',
    '```',
    'server/seed-data/<table>.csv',
    '```',
    '',
    "If the file exists, every row gets imported. If it doesn't, the backend falls back to 3–5 lorem-ipsum placeholder rows so the UI is never empty.",
    '',
    '## CSV format',
    '',
    '- One header row, with column names matching the table schema in `server/db.js` (or `server/database.py`). Look there to see what columns exist.',
    "- Skip the `id` column — it's auto-assigned by SQLite.",
    "- One data row per record. Standard CSV escaping rules apply (quoted strings for values containing commas or quotes).",
    '- Plain UTF-8 text. Export from Excel via **File → Save As → CSV UTF-8 (Comma delimited)**.',
    '',
    'Example for a `projects` table with columns `(id, name, description, imageUrl)`:',
    '',
    '```csv',
    'name,description,imageUrl',
    'Atlas,A bold civic-data dashboard project.,/sample-assets/projects-1.jpg',
    'Beacon,"Real-time analytics, focused on edge devices.",/sample-assets/projects-2.jpg',
    'Cascade,Survey aggregation built for clinicians.,/sample-assets/projects-3.jpg',
    '```',
    '',
    '## Limitations (v1)',
    '',
    "- **CSV only.** No native `.xlsx` parsing — open in Excel, **Save As CSV**, then drop the CSV here. (DemoKit ships with `csv-parse` for the Node stack and Python's stdlib `csv` module for the FastAPI stack; adding `xlsx` support is a future feature, not a hard limitation.)",
    "- **No BLOBs.** Files like PDFs, images, or videos cannot be inlined into the CSV. Drop those into `client/public/sample-assets/` instead and reference them by URL in the relevant column.",
    "- **Schema must match.** The CSV's column names must match the table's column names exactly (case-sensitive). Unknown columns are ignored; missing required columns will crash the seed.",
    "- **Re-running the seed:** delete the SQLite DB file (usually `dev.db` in the project root) and restart the backend. The seed only runs when a table is empty.",
    '',
    '## When to use this vs. `client/public/sample-assets/`',
    '',
    '| You have… | Drop it in… |',
    '|---|---|',
    '| Real database rows (records, entries, responses) | `server/seed-data/<table>.csv` |',
    '| Real images, PDFs, or downloadable files | `client/public/sample-assets/` |',
    '| Both | Use both folders together — the CSV references file URLs that resolve into `sample-assets/` |',
    '',
  ].join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function escapeHtml(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function deriveBackendPort(contract, stackId) {
  const stack = getStack(stackId);
  const fromContract = contract?.backendEnv?.PORT;
  const asNum = Number(fromContract);
  if (Number.isFinite(asNum) && asNum > 0) return asNum;
  const fromStack = Number(stack.defaultBackendEnv?.PORT);
  return Number.isFinite(fromStack) && fromStack > 0 ? fromStack : 8000;
}

function safeProjectName(projectName) {
  const slug = String(projectName || 'prototype')
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64);
  return slug || 'prototype';
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Write every deterministic wrapper file for a finished project.
 *
 * @param {{
 *   sessionId: string,
 *   projectName: string,
 *   stack: 'stack-a' | 'stack-b',
 *   contract: object,
 * }} args
 * @returns {Promise<string[]>} relative paths written, in write order
 */
export async function scaffoldProject({
  sessionId,
  projectName,
  stack,
  contract,
}) {
  if (!sessionId) throw new TypeError('scaffoldProject: sessionId is required');
  if (!stack) throw new TypeError('scaffoldProject: stack is required');

  // Validate stack early — getStack throws on unknown ids, which gives
  // a clearer error than failing inside a write below.
  getStack(stack);

  const name = safeProjectName(projectName);
  const backendPort = deriveBackendPort(contract, stack);
  const written = [];

  async function write(relPath, content) {
    await writeOutputFile(sessionId, relPath, content);
    written.push(relPath);
  }

  await write('client/index.html', indexHtml(name));
  await write('client/vite.config.js', viteConfig(backendPort));
  await write('client/package.json', clientPackageJson(name));

  // React bootstrap and the error boundary are scaffolded (not LLM-written)
  // so the router root lives in exactly one place. See mainJsx() comment
  // above for the bug class this prevents.
  await write('client/src/main.jsx', mainJsx());
  await write('client/src/ErrorBoundary.jsx', errorBoundary());

  if (stack === 'stack-b') {
    await write('server/package.json', stackBServerPackageJson(name));
    await write('package.json', rootPackageJsonStackB(name));
  } else {
    await write('server/requirements.txt', STACK_A_REQUIREMENTS);
    await write('package.json', rootPackageJsonStackA(name));
  }

  await write('.env.example', envExample(contract));
  await write('.gitignore', gitignore());

  // Empty asset drop folder for the human demo runner. Materialised via a
  // README so the directory exists in git/zip output without needing a
  // .gitkeep — the README also documents the drop-files-here UX. The
  // backend seed (written by the coder) references stable URLs
  // /sample-assets/<table>-<n>.<ext> that get resolved here.
  await write(
    'client/public/sample-assets/README.md',
    sampleAssetsReadme(name)
  );

  // Empty seed-data folder for real-row imports. The coder's DB init
  // file looks here first (e.g. server/seed-data/projects.csv) and
  // falls back to lorem-ipsum placeholders if the file isn't present.
  // Materialised via a README for the same reasons as sample-assets/.
  await write('server/seed-data/README.md', seedDataReadme(name));

  return written;
}

// Exposed for unit tests / future reuse.
export const _internals = Object.freeze({
  indexHtml,
  viteConfig,
  mainJsx,
  errorBoundary,
  clientPackageJson,
  stackBServerPackageJson,
  rootPackageJsonStackB,
  rootPackageJsonStackA,
  envExample,
  gitignore,
  sampleAssetsReadme,
  seedDataReadme,
  deriveBackendPort,
  safeProjectName,
});
